spring.datasource.url=jdbc:postgresql://localhost:5435/mydb
spring.datasource.username=myuser
spring.datasource.password=mypass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
management.endpoints.web.exposure.include=health,info
logging.level.org.springframework=debug


# optional: specify schema if you’re using it everywhere
# spring.jpa.properties.hibernate.default_schema=customer_order_microservice



